language: cpp

compiler:
  - gcc
  - clang
  
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
    packages:
      - g++-6
      - clang-3.8
      - python-numpy
      - openmpi-bin
      - libopenmpi-dev
env:
  global:
    - LOCAL_INSTALL="$HOME/local"
    - CPLUS_INCLUDE_PATH="$LOCAL_INSTALL/include"
    - LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$LOCAL_INSTALL/lib"
    - LIBRARY_PATH="$LIBRARY_PATH:$LOCAL_INSTALL/lib"

  matrix:
    - MPI=off
    - MPI=on

cache:
  directories:
    - $LOCAL_INSTALL

before_install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-6"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.8"; fi
  - export OMPI_CXX=$CXX
  - if [ "$MPI" = "on" ]; then export CXX="mpicxx"; fi

install:
  - $TRAVIS_BUILD_DIR/tools/travis-install-dependencies.sh $LOCAL_INSTALL
  
before_script:
  - mkdir $TRAVIS_BUILD_DIR/tests

script:
  - cd $TRAVIS_BUILD_DIR
  - scons -j 2 petsc=off mpi=$MPI python=on compiler=$CXX
  - cd tests
  - if [ "$MPI" = "off" ]; then ../build/last/binprecice test ../.ci-test-config.xml ../src > unit-test-output; fi
  - if [ "$MPI" = "off" ]; then ../build/last/binprecice test ../.ci-integration-test-config.xml ../src > integration-test-output; fi
  - if [ "$MPI" = "on"  ]; then mpirun.openmpi -n 4 ../build/last/binprecice test ../.ci-test-config.xml ../src > unit-test-output; fi
  - if [ "$MPI" = "on"  ]; then mpirun.openmpi -n 4 ../build/last/binprecice test ../.ci-integration-test-config.xml ../src > integration-test-output; fi
  
after_failure:
  - cd $TRAVIS_BUILD_DIR
  - cat config.log
  - cat ./tests/unit-test-output
  - cat ./tests/integration-test-output
